export const LANGS = {
  ru: { name:'Русский',  locale:'ru-RU', speech:'ru-RU' },
  en: { name:'English',  locale:'en-US', speech:'en-US' },
  lv: { name:'Latviešu', locale:'lv-LV', speech:'lv-LV' },
  zh: { name:'中文',      locale:'zh-CN', speech:'zh-CN' },
};

export const I18N = {
  ru: {
    'app.title':'Подсчёт',
    'app.untitled':'Без названия',
    'voice.title':'Голосовой ввод',
    'settings.title':'Настройки',
    'categories.title':'Категории',
    'csv':'CSV',
    'reset':'Обнулить',
    'save':'💾 Сохранить',
    'more':'Ещё',
    'close':'Закрыть',
    'calc.mulRows':'Умножить ряды',
    'photo.section':'Фото позиции',
    'photo.camera':'Снять фото',
    'photo.gallery':'Из галереи',
    'photo.remove':'🗑 Убрать фото',
    'edit':'✏️ Изменить',
    'delete':'🗑 Удалить',
    'calc.title':'Умножить',
    'calc.sub':'Ряды × В ряду',
    'calc.rows':'Рядов',
    'calc.cols':'В ряду',
    'calc.each':'Позиций в ящике',
    'calc.total':'Итого',
    'cancel':'Отмена',
    'calc.subtract':'− Вычесть',
    'calc.add':'+ Добавить',
    'multiply':'Умножить',
    'counter.reset':'Сброс',
    'settings.tileView':'Вид плиток',
    'settings.tileStyle':'Стиль плиток',
    'settings.tileClassic':'Классический',
    'settings.tileGlow':'Радиальное свечение',
    'settings.tileDiagonal':'Диагональный оттенок',
    'settings.tileRound':'Круглый счётчик',
    'settings.tileConvex':'Выпуклый',
    'settings.tileGlass':'Стеклянная панель',
    'settings.cols':'Плиток в ряду (столбцов)',
    'settings.auto':'Авто',
    'settings.rowsVisible':'Рядов на экране',
    'settings.rows':'Ряды',
    'settings.decrease':'Уменьшить',
    'settings.increase':'Увеличить',
    'settings.direction':'Направление',
    'settings.ltr':'Слева → вправо',
    'settings.rtl':'Справа → влево',
    'settings.catAlign':'Название категории',
    'settings.alignLeft':'Слева',
    'settings.alignCenter':'По центру',
    'settings.alignRight':'Справа',
    'settings.textSize':'Размер текста',
    'settings.qtySize':'Размер счётчика',
    'settings.small':'Мелкий',
    'settings.medium':'Обычный',
    'settings.large':'Крупный',
    'settings.language':'Язык',
    'settings.theme':'Тема',
    'settings.themeAuto':'Авто',
    'settings.themeLight':'Светлая',
    'settings.themeDark':'Тёмная',
    'settings.themeOled':'OLED',
    'settings.contrast':'Контраст',
    'settings.contrastNormal':'Обычный',
    'settings.contrastHigh':'Высокий',
    'settings.accent':'Акцентный цвет',
    'accent.green':'Зелёный',
    'accent.blue':'Синий',
    'accent.violet':'Фиолетовый',
    'accent.pink':'Розовый',
    'accent.amber':'Янтарный',
    'accent.cyan':'Голубой',
    'reorder.title':'Перестановка плиток',
    'reorder.on':'Перетащите плитки; бросайте в пустые ячейки, чтобы оставить пропуски',
    'reorder.done':'Порядок сохранён',
    'editor.newItem':'Новая позиция',
    'editor.subItem':'Введите название и категорию',
    'editor.name':'Название',
    'editor.namePh':'Например: Кега 20 л',
    'editor.category':'Категория',
    'editor.categoryPh':'Например: Кеги',
    'editor.nameCategory':'Название категории',
    'editor.nameCategoryPh':'Например: Кеги',
    'editor.newCategory':'Новая категория',
    'editor.subNewCategory':'Введите название раздела',
    'editor.editCategory':'Изменить категорию',
    'editor.subEditCategory':'Новое имя отобразится у всех её позиций',
    'editor.editItem':'Изменить позицию',
    'editor.subEditItem':'Переименуйте или смените категорию',
    'editor.save':'✓ Сохранить',
    'cats.sub':'Переименуйте, удалите или добавьте раздел',
    'cats.add':'+ Добавить категорию',
    'cats.empty':'Пока нет ни одной категории',
    'cats.rename':'Переименовать',
    'cats.delete':'Удалить',
    'cats.deleteEmptyTitle':'Удалить категорию?',
    'cats.deleteEmptyMsg':'Категория «{cat}» пуста.',
    'cats.hasTitle':'Категория «{cat}»',
    'cats.hasMsg':'Содержит {n} {word}. Что сделать?',
    'cats.delAll':'Удалить вместе с позициями',
    'cats.orphan':'Перенести в «Без категории»',
    'addTile.title':'Добавить позицию',
    'reset.title':'Начать новый подсчёт?',
    'reset.msg':'Название документа будет очищено, а все счётчики — обнулены.\nПозиции, категории, фото и настройки останутся.',
    'reset.confirm':'Начать заново',
    'delete.title':'Удалить позицию?',
    'delete.msg':'«{name}» будет удалена вместе с количеством и фото.',
    'delete.confirm':'Удалить',
    'save.savedTitle':'Сохранено',
    'save.savedMsg':'Файл перезаписан. Все изменения теперь внутри него.',
    'save.downloadTitle':'Файл сохранён',
    'save.downloadMsg':'Файл «{filename}» скачан в папку «Загрузки».\n\nЗамените им текущий файл приложения — тогда все изменения сохранятся внутри HTML и поедут вместе с ним на любое устройство.',
    'save.understood':'Понятно',
    'save.failMsg':'Не удалось собрать файл: {msg}',
    'validate.category':'Введите название категории',
    'validate.item':'Введите название позиции',
    'validate.dupCat':'Такая категория уже есть',
    'img.error':'Не удалось прочитать изображение',
    'csv.name':'Название',
    'csv.date':'Дата',
    'csv.category':'Категория',
    'csv.item':'Позиция',
    'csv.qty':'Количество',
    'slug.default':'подсчёт',
    'voice.off':'Голосовой ввод выключен',
    'voice.selectFirst':'Сначала выберите позицию',
    'voice.selected':'Выбрано: {name}',
    'voice.notUnderstood':'Не понял: {text}',
    'voice.unsupported':'Голосовой ввод не поддерживается. Откройте в Chrome, Edge или Safari.',
    'voice.listening':'Слушаю...',
    'voice.noMic':'Нет доступа к микрофону. Проверьте HTTPS и разрешения.',
    'items.one':'позицию',
    'items.few':'позиции',
    'items.many':'позиций',
  },
  en: {
    'app.title':'Count',
    'app.untitled':'Untitled',
    'voice.title':'Voice input',
    'settings.title':'Settings',
    'categories.title':'Categories',
    'csv':'CSV',
    'reset':'Reset',
    'save':'💾 Save',
    'more':'More',
    'close':'Close',
    'calc.mulRows':'Multiply rows',
    'photo.section':'Item photo',
    'photo.camera':'Take photo',
    'photo.gallery':'From gallery',
    'photo.remove':'🗑 Remove photo',
    'edit':'✏️ Edit',
    'delete':'🗑 Delete',
    'calc.title':'Multiply',
    'calc.sub':'Rows × Per row',
    'calc.rows':'Rows',
    'calc.cols':'Per row',
    'calc.each':'Items per box',
    'calc.total':'Total',
    'cancel':'Cancel',
    'calc.subtract':'− Subtract',
    'calc.add':'+ Add',
    'multiply':'Multiply',
    'counter.reset':'Reset',
    'settings.tileView':'Tile view',
    'settings.tileStyle':'Tile style',
    'settings.tileClassic':'Classic',
    'settings.tileGlow':'Radial glow',
    'settings.tileDiagonal':'Diagonal tint',
    'settings.tileRound':'Round counter',
    'settings.tileConvex':'Convex',
    'settings.tileGlass':'Glass bar',
    'settings.cols':'Tiles per row (columns)',
    'settings.auto':'Auto',
    'settings.rowsVisible':'Rows visible on screen',
    'settings.rows':'Rows',
    'settings.decrease':'Decrease',
    'settings.increase':'Increase',
    'settings.direction':'Direction',
    'settings.ltr':'Left → right',
    'settings.rtl':'Right → left',
    'settings.catAlign':'Category name',
    'settings.alignLeft':'Left',
    'settings.alignCenter':'Center',
    'settings.alignRight':'Right',
    'settings.textSize':'Text size',
    'settings.qtySize':'Counter size',
    'settings.small':'Small',
    'settings.medium':'Normal',
    'settings.large':'Large',
    'settings.language':'Language',
    'settings.theme':'Theme',
    'settings.themeAuto':'Auto',
    'settings.themeLight':'Light',
    'settings.themeDark':'Dark',
    'settings.themeOled':'OLED',
    'settings.contrast':'Contrast',
    'settings.contrastNormal':'Normal',
    'settings.contrastHigh':'High',
    'settings.accent':'Accent color',
    'accent.green':'Green',
    'accent.blue':'Blue',
    'accent.violet':'Violet',
    'accent.pink':'Pink',
    'accent.amber':'Amber',
    'accent.cyan':'Cyan',
    'reorder.title':'Rearrange tiles',
    'reorder.on':'Drag tiles to rearrange; drop into empty cells to leave gaps',
    'reorder.done':'Order saved',
    'editor.newItem':'New item',
    'editor.subItem':'Enter name and category',
    'editor.name':'Name',
    'editor.namePh':'E.g.: Keg 20 L',
    'editor.category':'Category',
    'editor.categoryPh':'E.g.: Kegs',
    'editor.nameCategory':'Category name',
    'editor.nameCategoryPh':'E.g.: Kegs',
    'editor.newCategory':'New category',
    'editor.subNewCategory':'Enter the section name',
    'editor.editCategory':'Edit category',
    'editor.subEditCategory':'The new name will appear on all its items',
    'editor.editItem':'Edit item',
    'editor.subEditItem':'Rename or change the category',
    'editor.save':'✓ Save',
    'cats.sub':'Rename, delete or add a section',
    'cats.add':'+ Add category',
    'cats.empty':'No categories yet',
    'cats.rename':'Rename',
    'cats.delete':'Delete',
    'cats.deleteEmptyTitle':'Delete category?',
    'cats.deleteEmptyMsg':'Category “{cat}” is empty.',
    'cats.hasTitle':'Category “{cat}”',
    'cats.hasMsg':'Contains {n} {word}. What to do?',
    'cats.delAll':'Delete with items',
    'cats.orphan':'Move to “Uncategorized”',
    'addTile.title':'Add item',
    'reset.title':'Start a new count?',
    'reset.msg':'The document name will be cleared and all counters reset.\nItems, categories, photos and settings will remain.',
    'reset.confirm':'Start over',
    'delete.title':'Delete item?',
    'delete.msg':'“{name}” will be deleted along with its quantity and photo.',
    'delete.confirm':'Delete',
    'save.savedTitle':'Saved',
    'save.savedMsg':'File overwritten. All changes are now inside it.',
    'save.downloadTitle':'File saved',
    'save.downloadMsg':'File “{filename}” was downloaded to “Downloads”.\n\nReplace the current app file with it — all changes will be stored inside the HTML and travel with it to any device.',
    'save.understood':'Got it',
    'save.failMsg':'Could not build the file: {msg}',
    'validate.category':'Enter a category name',
    'validate.item':'Enter an item name',
    'validate.dupCat':'This category already exists',
    'img.error':'Could not read the image',
    'csv.name':'Name',
    'csv.date':'Date',
    'csv.category':'Category',
    'csv.item':'Item',
    'csv.qty':'Quantity',
    'slug.default':'count',
    'voice.off':'Voice input off',
    'voice.selectFirst':'Select an item first',
    'voice.selected':'Selected: {name}',
    'voice.notUnderstood':'Did not understand: {text}',
    'voice.unsupported':'Voice input is not supported. Open in Chrome, Edge or Safari.',
    'voice.listening':'Listening...',
    'voice.noMic':'No microphone access. Check HTTPS and permissions.',
    'items.one':'item',
    'items.few':'items',
    'items.many':'items',
  },
  lv: {
    'app.title':'Skaitīšana',
    'app.untitled':'Bez nosaukuma',
    'voice.title':'Balss ievade',
    'settings.title':'Iestatījumi',
    'categories.title':'Kategorijas',
    'csv':'CSV',
    'reset':'Nodzēst',
    'save':'💾 Saglabāt',
    'more':'Vairāk',
    'close':'Aizvērt',
    'calc.mulRows':'Reizināt rindas',
    'photo.section':'Pozīcijas foto',
    'photo.camera':'Uzņemt foto',
    'photo.gallery':'No galerijas',
    'photo.remove':'🗑 Noņemt foto',
    'edit':'✏️ Mainīt',
    'delete':'🗑 Dzēst',
    'calc.title':'Reizināt',
    'calc.sub':'Rindas × Rindā',
    'calc.rows':'Rindas',
    'calc.cols':'Rindā',
    'calc.each':'Vienības kastē',
    'calc.total':'Kopā',
    'cancel':'Atcelt',
    'calc.subtract':'− Atņemt',
    'calc.add':'+ Pievienot',
    'multiply':'Reizināt',
    'counter.reset':'Atiestatīt',
    'settings.tileView':'Flīžu skats',
    'settings.tileStyle':'Flīžu stils',
    'settings.tileClassic':'Klasiskais',
    'settings.tileGlow':'Radiāls spīdums',
    'settings.tileDiagonal':'Diagonāls tonis',
    'settings.tileRound':'Apaļš skaitītājs',
    'settings.tileConvex':'Izliekts',
    'settings.tileGlass':'Stikla josla',
    'settings.cols':'Flīzes rindā (kolonnas)',
    'settings.auto':'Auto',
    'settings.rowsVisible':'Redzamās rindas ekrānā',
    'settings.rows':'Rindas',
    'settings.decrease':'Samazināt',
    'settings.increase':'Palielināt',
    'settings.direction':'Virziens',
    'settings.ltr':'No kreisās → uz labo',
    'settings.rtl':'No labās → uz kreiso',
    'settings.catAlign':'Kategorijas nosaukums',
    'settings.alignLeft':'Pa kreisi',
    'settings.alignCenter':'Centrā',
    'settings.alignRight':'Pa labi',
    'settings.textSize':'Teksta izmērs',
    'settings.qtySize':'Skaitītāja izmērs',
    'settings.small':'Mazs',
    'settings.medium':'Parasts',
    'settings.large':'Liels',
    'settings.language':'Valoda',
    'settings.theme':'Tēma',
    'settings.themeAuto':'Auto',
    'settings.themeLight':'Gaišā',
    'settings.themeDark':'Tumšā',
    'settings.themeOled':'OLED',
    'settings.contrast':'Kontrasts',
    'settings.contrastNormal':'Parasts',
    'settings.contrastHigh':'Augsts',
    'settings.accent':'Akcenta krāsa',
    'accent.green':'Zaļš',
    'accent.blue':'Zils',
    'accent.violet':'Violets',
    'accent.pink':'Rozā',
    'accent.amber':'Dzintara',
    'accent.cyan':'Ciāna',
    'reorder.title':'Pārkārtot flīzes',
    'reorder.on':'Velciet flīzes; nometiet tukšās šūnās, lai atstātu atstarpes',
    'reorder.done':'Secība saglabāta',
    'editor.newItem':'Jauna pozīcija',
    'editor.subItem':'Ievadiet nosaukumu un kategoriju',
    'editor.name':'Nosaukums',
    'editor.namePh':'Piemēram: Kega 20 l',
    'editor.category':'Kategorija',
    'editor.categoryPh':'Piemēram: Kegas',
    'editor.nameCategory':'Kategorijas nosaukums',
    'editor.nameCategoryPh':'Piemēram: Kegas',
    'editor.newCategory':'Jauna kategorija',
    'editor.subNewCategory':'Ievadiet sadaļas nosaukumu',
    'editor.editCategory':'Mainīt kategoriju',
    'editor.subEditCategory':'Jaunais nosaukums parādīsies visām tās pozīcijām',
    'editor.editItem':'Mainīt pozīciju',
    'editor.subEditItem':'Pārdēvējiet vai mainiet kategoriju',
    'editor.save':'✓ Saglabāt',
    'cats.sub':'Pārdēvējiet, dzēsiet vai pievienojiet sadaļu',
    'cats.add':'+ Pievienot kategoriju',
    'cats.empty':'Vēl nav nevienas kategorijas',
    'cats.rename':'Pārdēvēt',
    'cats.delete':'Dzēst',
    'cats.deleteEmptyTitle':'Dzēst kategoriju?',
    'cats.deleteEmptyMsg':'Kategorija “{cat}” ir tukša.',
    'cats.hasTitle':'Kategorija “{cat}”',
    'cats.hasMsg':'Satur {n} {word}. Ko darīt?',
    'cats.delAll':'Dzēst kopā ar pozīcijām',
    'cats.orphan':'Pārvietot uz “Bez kategorijas”',
    'addTile.title':'Pievienot pozīciju',
    'reset.title':'Sākt jaunu skaitīšanu?',
    'reset.msg':'Dokumenta nosaukums tiks notīrīts, un visi skaitītāji tiks nodzēsti.\nPozīcijas, kategorijas, foto un iestatījumi paliks.',
    'reset.confirm':'Sākt no jauna',
    'delete.title':'Dzēst pozīciju?',
    'delete.msg':'“{name}” tiks dzēsta kopā ar daudzumu un foto.',
    'delete.confirm':'Dzēst',
    'save.savedTitle':'Saglabāts',
    'save.savedMsg':'Fails pārrakstīts. Visas izmaiņas tagad ir tajā.',
    'save.downloadTitle':'Fails saglabāts',
    'save.downloadMsg':'Fails “{filename}” lejupielādēts mapē “Lejupielādes”.\n\nAizstājiet ar to pašreizējo lietotnes failu — tad visas izmaiņas saglabāsies HTML iekšienē un ceļos kopā ar to uz jebkuru ierīci.',
    'save.understood':'Saprotu',
    'save.failMsg':'Neizdevās izveidot failu: {msg}',
    'validate.category':'Ievadiet kategorijas nosaukumu',
    'validate.item':'Ievadiet pozīcijas nosaukumu',
    'validate.dupCat':'Šāda kategorija jau pastāv',
    'img.error':'Neizdevās nolasīt attēlu',
    'csv.name':'Nosaukums',
    'csv.date':'Datums',
    'csv.category':'Kategorija',
    'csv.item':'Pozīcija',
    'csv.qty':'Daudzums',
    'slug.default':'skaitisana',
    'voice.off':'Balss ievade izslēgta',
    'voice.selectFirst':'Vispirms izvēlieties pozīciju',
    'voice.selected':'Izvēlēts: {name}',
    'voice.notUnderstood':'Nesapratu: {text}',
    'voice.unsupported':'Balss ievade netiek atbalstīta. Atveriet Chrome, Edge vai Safari.',
    'voice.listening':'Klausos...',
    'voice.noMic':'Nav piekļuves mikrofonam. Pārbaudiet HTTPS un atļaujas.',
    'items.one':'pozīciju',
    'items.few':'pozīcijas',
    'items.many':'pozīcijas',
  },
  zh: {
    'app.title':'计数',
    'app.untitled':'无标题',
    'voice.title':'语音输入',
    'settings.title':'设置',
    'categories.title':'分类',
    'csv':'CSV',
    'reset':'清零',
    'save':'💾 保存',
    'more':'更多',
    'close':'关闭',
    'calc.mulRows':'相乘行数',
    'photo.section':'商品照片',
    'photo.camera':'拍照',
    'photo.gallery':'从相册选择',
    'photo.remove':'🗑 移除照片',
    'edit':'✏️ 编辑',
    'delete':'🗑 删除',
    'calc.title':'相乘',
    'calc.sub':'行数 × 每行',
    'calc.rows':'行数',
    'calc.cols':'每行',
    'calc.each':'每箱数量',
    'calc.total':'合计',
    'cancel':'取消',
    'calc.subtract':'− 减去',
    'calc.add':'+ 添加',
    'multiply':'相乘',
    'counter.reset':'重置',
    'settings.tileView':'方块视图',
    'settings.tileStyle':'方块样式',
    'settings.tileClassic':'经典',
    'settings.tileGlow':'径向光晕',
    'settings.tileDiagonal':'对角渐变',
    'settings.tileRound':'圆形计数',
    'settings.tileConvex':'凸起',
    'settings.tileGlass':'玻璃条',
    'settings.cols':'每行方块数（列）',
    'settings.auto':'自动',
    'settings.rowsVisible':'屏幕可见行数',
    'settings.rows':'行数',
    'settings.decrease':'减少',
    'settings.increase':'增加',
    'settings.direction':'方向',
    'settings.ltr':'从左到右',
    'settings.rtl':'从右到左',
    'settings.catAlign':'分类名称',
    'settings.alignLeft':'左',
    'settings.alignCenter':'居中',
    'settings.alignRight':'右',
    'settings.textSize':'文字大小',
    'settings.qtySize':'计数器大小',
    'settings.small':'小',
    'settings.medium':'正常',
    'settings.large':'大',
    'settings.language':'语言',
    'settings.theme':'主题',
    'settings.themeAuto':'自动',
    'settings.themeLight':'浅色',
    'settings.themeDark':'深色',
    'settings.themeOled':'OLED',
    'settings.contrast':'对比度',
    'settings.contrastNormal':'普通',
    'settings.contrastHigh':'高',
    'settings.accent':'强调色',
    'accent.green':'绿色',
    'accent.blue':'蓝色',
    'accent.violet':'紫色',
    'accent.pink':'粉色',
    'accent.amber':'琥珀色',
    'accent.cyan':'青色',
    'reorder.title':'排列方块',
    'reorder.on':'拖动方块重新排列；放入空单元格可留出间隔',
    'reorder.done':'顺序已保存',
    'editor.newItem':'新项目',
    'editor.subItem':'输入名称和分类',
    'editor.name':'名称',
    'editor.namePh':'例如：20升桶',
    'editor.category':'分类',
    'editor.categoryPh':'例如：桶',
    'editor.nameCategory':'分类名称',
    'editor.nameCategoryPh':'例如：桶',
    'editor.newCategory':'新分类',
    'editor.subNewCategory':'输入分区名称',
    'editor.editCategory':'编辑分类',
    'editor.subEditCategory':'新名称将显示在其所有项目上',
    'editor.editItem':'编辑项目',
    'editor.subEditItem':'重命名或更改分类',
    'editor.save':'✓ 保存',
    'cats.sub':'重命名、删除或添加分区',
    'cats.add':'+ 添加分类',
    'cats.empty':'还没有任何分类',
    'cats.rename':'重命名',
    'cats.delete':'删除',
    'cats.deleteEmptyTitle':'删除分类？',
    'cats.deleteEmptyMsg':'分类“{cat}”是空的。',
    'cats.hasTitle':'分类“{cat}”',
    'cats.hasMsg':'包含 {n} {word}。要怎么做？',
    'cats.delAll':'连同项目一起删除',
    'cats.orphan':'移动到“未分类”',
    'addTile.title':'添加项目',
    'reset.title':'开始新的计数？',
    'reset.msg':'文档名称将被清除，所有计数器将归零。\n项目、分类、照片和设置将保留。',
    'reset.confirm':'重新开始',
    'delete.title':'删除项目？',
    'delete.msg':'“{name}”将连同数量和照片一起删除。',
    'delete.confirm':'删除',
    'save.savedTitle':'已保存',
    'save.savedMsg':'文件已覆盖。所有更改现在都在其中。',
    'save.downloadTitle':'文件已保存',
    'save.downloadMsg':'文件“{filename}”已下载到“下载”文件夹。\n\n用它替换当前应用文件——这样所有更改都会保存在 HTML 内，并随它一起到任何设备。',
    'save.understood':'知道了',
    'save.failMsg':'无法生成文件：{msg}',
    'validate.category':'请输入分类名称',
    'validate.item':'请输入项目名称',
    'validate.dupCat':'该分类已存在',
    'img.error':'无法读取图像',
    'csv.name':'名称',
    'csv.date':'日期',
    'csv.category':'分类',
    'csv.item':'项目',
    'csv.qty':'数量',
    'slug.default':'count',
    'voice.off':'语音输入已关闭',
    'voice.selectFirst':'请先选择一个项目',
    'voice.selected':'已选择：{name}',
    'voice.notUnderstood':'未听懂：{text}',
    'voice.unsupported':'不支持语音输入。请在 Chrome、Edge 或 Safari 中打开。',
    'voice.listening':'正在聆听...',
    'voice.noMic':'无法访问麦克风。请检查 HTTPS 和权限。',
    'items.one':'个项目',
    'items.few':'个项目',
    'items.many':'个项目',
  }
};

export const DEFAULT_ITEMS = {
  ru: [
    {id:'crateGrnE', name:'Ящик зелёный',        category:'Ящики пустые'},
    {id:'crateBluE', name:'Ящик синий',          category:'Ящики пустые'},
    {id:'crateBluF', name:'Синий с прозрачными', category:'Ящики с бутылками'},
    {id:'crateTub',  name:'Синий с Tuborg',      category:'Ящики с бутылками'},
    {id:'crateGrnF', name:'Зелёный с бутылками', category:'Ящики с бутылками'},
    {id:'crateGrnGarage', name:'Зелёный с Garage', category:'Ящики с бутылками'},
    {id:'keg15',     name:'Кега 15 л',           category:'Кеги'},
    {id:'keg20',     name:'Кега 20 л',           category:'Кеги'},
    {id:'keg20slim', name:'Кега 20 л узкая',     category:'Кеги'},
    {id:'keg30',     name:'Кега 30 л',           category:'Кеги'},
    {id:'palEUR',    name:'Паллета EUR',         category:'Паллеты'},
  ],
  en: [
    {id:'crateGrnE', name:'Green crate',             category:'Empty crates'},
    {id:'crateBluE', name:'Blue crate',              category:'Empty crates'},
    {id:'crateBluF', name:'Blue with clear bottles', category:'Crates with bottles'},
    {id:'crateTub',  name:'Blue with Tuborg',        category:'Crates with bottles'},
    {id:'crateGrnF', name:'Green with bottles',      category:'Crates with bottles'},
    {id:'crateGrnGarage', name:'Green with Garage',  category:'Crates with bottles'},
    {id:'keg15',     name:'Keg 15 L',                category:'Kegs'},
    {id:'keg20',     name:'Keg 20 L',                category:'Kegs'},
    {id:'keg20slim', name:'Keg 20 L slim',           category:'Kegs'},
    {id:'keg30',     name:'Keg 30 L',                category:'Kegs'},
    {id:'palEUR',    name:'EUR pallet',              category:'Pallets'},
  ],
  lv: [
    {id:'crateGrnE', name:'Zaļā kaste',           category:'Tukšas kastes'},
    {id:'crateBluE', name:'Zilā kaste',           category:'Tukšas kastes'},
    {id:'crateBluF', name:'Zilā ar caurspīdīgām', category:'Kastes ar pudelēm'},
    {id:'crateTub',  name:'Zilā ar Tuborg',       category:'Kastes ar pudelēm'},
    {id:'crateGrnF', name:'Zaļā ar pudelēm',      category:'Kastes ar pudelēm'},
    {id:'crateGrnGarage', name:'Zaļā ar Garage',  category:'Kastes ar pudelēm'},
    {id:'keg15',     name:'Kega 15 l',            category:'Kegas'},
    {id:'keg20',     name:'Kega 20 l',            category:'Kegas'},
    {id:'keg20slim', name:'Kega 20 l šaurā',      category:'Kegas'},
    {id:'keg30',     name:'Kega 30 l',            category:'Kegas'},
    {id:'palEUR',    name:'Palete EUR',           category:'Paletes'},
  ],
  zh: [
    {id:'crateGrnE', name:'绿色箱',       category:'空箱'},
    {id:'crateBluE', name:'蓝色箱',       category:'空箱'},
    {id:'crateBluF', name:'蓝色带透明瓶', category:'带瓶箱'},
    {id:'crateTub',  name:'蓝色带Tuborg', category:'带瓶箱'},
    {id:'crateGrnF', name:'绿色带瓶',     category:'带瓶箱'},
    {id:'crateGrnGarage', name:'绿色带Garage', category:'带瓶箱'},
    {id:'keg15',     name:'15升桶',       category:'桶'},
    {id:'keg20',     name:'20升桶',       category:'桶'},
    {id:'keg20slim', name:'20升窄桶',     category:'桶'},
    {id:'keg30',     name:'30升桶',       category:'桶'},
    {id:'palEUR',    name:'EUR托盘',      category:'托盘'},
  ],
};

/* Hosted images live in the repo /images folder. Relative paths resolve both on
   GitHub Pages and when the file is opened locally next to the images folder. */
export const IMAGE_BY_ID = {
  crateGrnE: 'images/crateGrnE.webp',
  crateBluE: 'images/crateBluE.webp',
  crateGrnF: 'images/crateGrnF.webp',
  crateBluF: 'images/crateBluF.webp',
  crateTub:  'images/crateTub.webp',
  crateGrnGarage: 'images/crateGrnGarage.webp',
  keg20:     'images/keg20.webp',
  keg20slim: 'images/keg20slim.webp',
  palEUR:    'images/palEUR.webp',
};


