import { I18N } from './catalog.js';
const extra = {
  en: { sessions:'Sessions', newCount:'New count', untitled:'Untitled count', saved:'Saved on this device', offline:'Offline · saved on this device', yourItems:'Your items', hint:'Tap +1 · Swipe −1 · Hold for more', grid:'Grid layout', gridHint:'Drag a tile to a square to place it. Drag empty space to move everything. Tap a gap to remove it.', autoArrange:'Auto arrange', removeGap:'Remove gap', undo:'Undo', redo:'Redo', add:'Add item', selected:'Selected item', empty:'No items found.', backup:'Download backup', restore:'Restore backup', backupHint:'All sessions and settings, in a reusable JSON file.', restoreHint:'Replace current data with a backup. You can undo this.', export:'Export this count (CSV)', reset:'Clear this count', resetHint:'Sets every quantity to zero. You can undo this.', newHint:'Keeps this count in history and starts a fresh count with the same items.', name:'Name', edit:'Edit', remove:'Delete', ungrouped:'Other items', categories:'Categories', all:'All', details:'Item details', quantity:'Quantity', set:'Set quantity', bulk:'Add a stack', perRow:'Per row', rows:'Rows', apply:'Apply', move:'Reorder items', moveHint:'Drag a tile onto another to swap places, or use the arrows.', moveUp:'Move earlier', moveDown:'Move later', confirm:'Confirm', cancel:'Cancel', voice:'Voice counting', voiceHint:'Select an item, then say “plus five”. Speech availability depends on your browser and connection.', stopVoice:'Stop listening', reload:'Reload to update', ready:'Available offline', recovery:'Could not load saved data. Your saved data has not been overwritten. Download it for recovery or restore a valid backup.', rawBackup:'Download saved data for recovery', 'settings.imageZoom':'Picture zoom', 'settings.titleSize':'Title size', 'settings.imageShift':'Picture position', 'imageNudge.up':'Move pictures up', 'imageNudge.down':'Move pictures down', 'imageNudge.left':'Move pictures left', 'imageNudge.right':'Move pictures right', 'imageNudge.center':'Center pictures' },
  lv: { sessions:'Sesijas', newCount:'Jauna uzskaite', untitled:'Uzskaite bez nosaukuma', saved:'Saglabāts šajā ierīcē', offline:'Bezsaistē · saglabāts ierīcē', yourItems:'Jūsu vienības', hint:'Pieskāriens +1 · Vilciens −1 · Turēt: vairāk', grid:'Režģa izkārtojums', gridHint:'Velciet flīzi uz kvadrātu, lai to novietotu. Velciet tukšo vietu, lai pārvietotu visu. Pieskarieties atstarpei, lai to noņemtu.', autoArrange:'Sakārtot automātiski', removeGap:'Noņemt atstarpi', undo:'Atsaukt', redo:'Atkārtot', add:'Pievienot', selected:'Izvēlētā vienība', empty:'Nav atrasta neviena vienība.', backup:'Lejupielādēt rezerves kopiju', restore:'Atjaunot rezerves kopiju', backupHint:'Visas sesijas un iestatījumi JSON failā.', restoreHint:'Aizstāt datus ar rezerves kopiju. To var atsaukt.', export:'Eksportēt uzskaiti (CSV)', reset:'Notīrīt šo uzskaiti', resetHint:'Iestata visus daudzumus uz nulli. To var atsaukt.', newHint:'Saglabā pašreizējo uzskaiti vēsturē un sāk jaunu ar tām pašām vienībām.', name:'Nosaukums', edit:'Rediģēt', remove:'Dzēst', ungrouped:'Citas vienības', categories:'Kategorijas', details:'Vienības dati', quantity:'Daudzums', set:'Iestatīt daudzumu', bulk:'Pievienot kaudzi', perRow:'Vienā rindā', rows:'Rindas', apply:'Lietot', move:'Mainīt secību', moveHint:'Velciet flīzi uz citu, lai samainītu vietām, vai izmantojiet bultiņas.', moveUp:'Pārvietot agrāk', moveDown:'Pārvietot vēlāk', confirm:'Apstiprināt', cancel:'Atcelt', voice:'Balss uzskaite', voiceHint:'Izvēlieties vienību, tad sakiet “plus pieci”. Pieejamība atkarīga no pārlūka un savienojuma.', stopVoice:'Pārtraukt klausīšanos', reload:'Pārlādēt atjaunināšanai', ready:'Pieejams bezsaistē', 'settings.imageZoom':'Attēla tālummaiņa', 'settings.titleSize':'Virsraksta izmērs', 'settings.imageShift':'Attēlu novietojums', 'imageNudge.up':'Pārvietot attēlus uz augšu', 'imageNudge.down':'Pārvietot attēlus uz leju', 'imageNudge.left':'Pārvietot attēlus pa kreisi', 'imageNudge.right':'Pārvietot attēlus pa labi', 'imageNudge.center':'Centrēt attēlus' },
  ru: { sessions:'Сессии', newCount:'Новый подсчёт', untitled:'Подсчёт без названия', saved:'Сохранено на устройстве', offline:'Без сети · сохранено на устройстве', yourItems:'Ваши позиции', hint:'Касание +1 · Смахивание −1 · Удержание: ещё', grid:'Сетка', gridHint:'Перетащите плитку в квадрат, чтобы разместить её. Потяните пустое место, чтобы сдвинуть всё. Коснитесь промежутка, чтобы убрать его.', autoArrange:'Упорядочить', removeGap:'Убрать промежуток', undo:'Отменить', redo:'Повторить', add:'Добавить', selected:'Выбранная позиция', empty:'Ничего не найдено.', backup:'Скачать резервную копию', restore:'Восстановить копию', backupHint:'Все сессии и настройки в файле JSON.', restoreHint:'Заменить данные резервной копией. Можно отменить.', export:'Экспорт подсчёта (CSV)', reset:'Очистить этот подсчёт', resetHint:'Обнулить все количества. Можно отменить.', newHint:'Сохранить текущий подсчёт в истории и начать новый с теми же позициями.', name:'Название', edit:'Изменить', remove:'Удалить', ungrouped:'Другие позиции', categories:'Категории', details:'Позиция', quantity:'Количество', set:'Задать количество', bulk:'Добавить стопку', perRow:'В ряду', rows:'Рядов', apply:'Применить', move:'Порядок позиций', moveHint:'Перетащите плитку на другую, чтобы поменять местами, или используйте стрелки.', moveUp:'Переместить раньше', moveDown:'Переместить позже', confirm:'Подтвердить', cancel:'Отмена', voice:'Голосовой подсчёт', voiceHint:'Выберите позицию и скажите «плюс пять». Доступность зависит от браузера и соединения.', stopVoice:'Остановить запись', reload:'Обновить приложение', ready:'Доступно без сети', 'settings.imageZoom':'Масштаб изображения', 'settings.titleSize':'Размер заголовка', 'settings.imageShift':'Положение изображения', 'imageNudge.up':'Сдвинуть изображения вверх', 'imageNudge.down':'Сдвинуть изображения вниз', 'imageNudge.left':'Сдвинуть изображения влево', 'imageNudge.right':'Сдвинуть изображения вправо', 'imageNudge.center':'Центрировать изображения' },
  zh: { sessions:'记录', newCount:'新建计数', untitled:'未命名计数', saved:'已保存在此设备', offline:'离线 · 已保存在此设备', yourItems:'物品', hint:'点击 +1 · 滑动 −1 · 长按查看更多', grid:'网格布局', gridHint:'将方块拖到格子中放置。拖动空白处可整体移动。点击空隙将其移除。', autoArrange:'自动排列', removeGap:'移除空隙', undo:'撤销', redo:'重做', add:'添加物品', selected:'选中的物品', empty:'未找到物品。', backup:'下载备份', restore:'恢复备份', backupHint:'所有记录和设置保存为 JSON 文件。', restoreHint:'用备份替换当前数据。可以撤销。', export:'导出计数 (CSV)', reset:'清空此计数', resetHint:'将所有数量设为零。可以撤销。', newHint:'保留当前记录，并使用相同物品开始新计数。', name:'名称', edit:'编辑', remove:'删除', ungrouped:'其他物品', categories:'类别', details:'物品详情', quantity:'数量', set:'设置数量', bulk:'批量添加', perRow:'每行', rows:'行数', apply:'应用', move:'调整顺序', moveHint:'将方块拖到另一个方块上即可交换位置，或使用箭头。', moveUp:'前移', moveDown:'后移', confirm:'确认', cancel:'取消', voice:'语音计数', voiceHint:'选择物品，然后说“加五”。可用性取决于浏览器和网络。', stopVoice:'停止聆听', reload:'重新加载更新', ready:'可离线使用', 'settings.imageZoom':'图片缩放', 'settings.titleSize':'标题大小', 'settings.imageShift':'图片位置', 'imageNudge.up':'上移图片', 'imageNudge.down':'下移图片', 'imageNudge.left':'左移图片', 'imageNudge.right':'右移图片', 'imageNudge.center':'居中图片' },
};
const deletion = {
  en: { deleteHint:'Delete this item and its quantity? You can undo this until the app is reloaded.', deleteCategoryHint:'Keep the items without a category, or delete the category and its items? You can undo this until the app is reloaded.' },
  lv: { deleteHint:'Dzēst šo vienību un tās daudzumu? To var atsaukt līdz lietotnes pārlādei.', deleteCategoryHint:'Saglabāt vienības bez kategorijas vai dzēst kategoriju kopā ar vienībām? To var atsaukt līdz pārlādei.' },
  ru: { deleteHint:'Удалить позицию и её количество? Можно отменить до перезагрузки приложения.', deleteCategoryHint:'Сохранить позиции без категории или удалить вместе с категорией? Можно отменить до перезагрузки.' },
  zh: { deleteHint:'删除此物品及其数量？重新加载应用前可以撤销。', deleteCategoryHint:'保留物品并移出类别，还是删除类别及其物品？重新加载前可以撤销。' },
};
const cloudStrings = {
  en: { cloudSync:'Excel sync', cloudHint:'Paste the Power Automate HTTP URL. Counts are sent automatically while online; changes made offline sync when the connection returns.', cloudUrl:'Power Automate URL', cloudSave:'Save', cloudNow:'Sync now', cloudSaved:'Sync URL saved.', cloudIdle:'Ready for your next count.', cloudReady:'Excel sync is on.', cloudPending:'Waiting to sync…', cloudSending:'Syncing to Excel…', cloudSynced:'Synced to Excel.', cloudError:'Sync failed — will retry.' },
  lv: { cloudSync:'Excel sinhronizācija', cloudHint:'Ielīmējiet Power Automate HTTP saiti. Uzskaites tiek sūtītas automātiski, kamēr ir savienojums; bezsaistē veiktās izmaiņas sinhronizējas, kad savienojums atgriežas.', cloudUrl:'Power Automate saite', cloudSave:'Saglabāt', cloudNow:'Sinhronizēt tagad', cloudSaved:'Sinhronizācijas saite saglabāta.', cloudIdle:'Gatavs nākamajai uzskaitei.', cloudReady:'Excel sinhronizācija ieslēgta.', cloudPending:'Gaida sinhronizāciju…', cloudSending:'Sinhronizē ar Excel…', cloudSynced:'Sinhronizēts ar Excel.', cloudError:'Sinhronizācija neizdevās — mēģinās vēlreiz.' },
  ru: { cloudSync:'Синхронизация Excel', cloudHint:'Вставьте HTTP-ссылку Power Automate. Данные отправляются автоматически при наличии сети; изменения, сделанные офлайн, синхронизируются при восстановлении связи.', cloudUrl:'Ссылка Power Automate', cloudSave:'Сохранить', cloudNow:'Синхронизировать', cloudSaved:'Ссылка синхронизации сохранена.', cloudIdle:'Готово к следующему подсчёту.', cloudReady:'Синхронизация Excel включена.', cloudPending:'Ожидание синхронизации…', cloudSending:'Синхронизация с Excel…', cloudSynced:'Синхронизировано с Excel.', cloudError:'Синхронизация не удалась — повторим.' },
  zh: { cloudSync:'Excel 同步', cloudHint:'粘贴 Power Automate HTTP 地址。联网时会自动发送计数；离线时的更改会在恢复连接后同步。', cloudUrl:'Power Automate 地址', cloudSave:'保存', cloudNow:'立即同步', cloudSaved:'同步地址已保存。', cloudIdle:'准备好开始下一次计数。', cloudReady:'Excel 同步已开启。', cloudPending:'等待同步…', cloudSending:'正在同步到 Excel…', cloudSynced:'已同步到 Excel。', cloudError:'同步失败——将重试。' },
};
export function translate(lang, key) { return deletion[lang]?.[key] ?? extra[lang]?.[key] ?? I18N[lang]?.[key] ?? cloudStrings[lang]?.[key] ?? extra.en[key] ?? cloudStrings.en[key] ?? I18N.en[key] ?? key; }
