import { I18N } from './catalog.js';
const extra = {
  en: { sessions:'Sessions', newCount:'New count', untitled:'Untitled count', saved:'Saved on this device', offline:'Offline · saved on this device', yourItems:'Your items', hint:'Tap +1 · Swipe −1 · Hold for more', search:'Find an item…', total:'Total counted', checked:'checked', undo:'Undo', redo:'Redo', add:'Add item', selected:'Selected item', empty:'No items found.', backup:'Download backup', restore:'Restore backup', backupHint:'All sessions and settings, in a reusable JSON file.', restoreHint:'Replace current data with a backup. You can undo this.', export:'Export this count (CSV)', reset:'Clear this count', resetHint:'Sets every quantity to zero. You can undo this.', newHint:'Keeps this count in history and starts a fresh count with the same items.', name:'Name', edit:'Edit', remove:'Delete', ungrouped:'Other items', categories:'Categories', all:'All', details:'Item details', quantity:'Quantity', set:'Set quantity', bulk:'Add a stack', perRow:'Per row', rows:'Rows', apply:'Apply', move:'Reorder items', moveHint:'Use the arrows to move items within a category.', confirm:'Confirm', cancel:'Cancel', voice:'Voice counting', voiceHint:'Select an item, then say “plus five”. Speech availability depends on your browser and connection.', stopVoice:'Stop listening', reload:'Reload to update', ready:'Available offline', recovery:'Could not load saved data. Your saved data has not been overwritten. Download it for recovery or restore a valid backup.', rawBackup:'Download saved data for recovery' },
  lv: { sessions:'Sesijas', newCount:'Jauna uzskaite', untitled:'Uzskaite bez nosaukuma', saved:'Saglabāts šajā ierīcē', offline:'Bezsaistē · saglabāts ierīcē', yourItems:'Jūsu vienības', hint:'Pieskāriens +1 · Vilciens −1 · Turēt: vairāk', search:'Meklēt vienību…', total:'Kopā saskaitīts', checked:'pārbaudītas', undo:'Atsaukt', redo:'Atkārtot', add:'Pievienot', selected:'Izvēlētā vienība', empty:'Nav atrasta neviena vienība.', backup:'Lejupielādēt rezerves kopiju', restore:'Atjaunot rezerves kopiju', backupHint:'Visas sesijas un iestatījumi JSON failā.', restoreHint:'Aizstāt datus ar rezerves kopiju. To var atsaukt.', export:'Eksportēt uzskaiti (CSV)', reset:'Notīrīt šo uzskaiti', resetHint:'Iestata visus daudzumus uz nulli. To var atsaukt.', newHint:'Saglabā pašreizējo uzskaiti vēsturē un sāk jaunu ar tām pašām vienībām.', name:'Nosaukums', edit:'Rediģēt', remove:'Dzēst', ungrouped:'Citas vienības', categories:'Kategorijas', details:'Vienības dati', quantity:'Daudzums', set:'Iestatīt daudzumu', bulk:'Pievienot kaudzi', perRow:'Vienā rindā', rows:'Rindas', apply:'Lietot', move:'Mainīt secību', moveHint:'Izmantojiet bultiņas, lai mainītu secību kategorijā.', confirm:'Apstiprināt', cancel:'Atcelt', voice:'Balss uzskaite', voiceHint:'Izvēlieties vienību, tad sakiet “plus pieci”. Pieejamība atkarīga no pārlūka un savienojuma.', stopVoice:'Pārtraukt klausīšanos', reload:'Pārlādēt atjaunināšanai', ready:'Pieejams bezsaistē' },
  ru: { sessions:'Сессии', newCount:'Новый подсчёт', untitled:'Подсчёт без названия', saved:'Сохранено на устройстве', offline:'Без сети · сохранено на устройстве', yourItems:'Ваши позиции', hint:'Касание +1 · Смахивание −1 · Удержание: ещё', search:'Найти позицию…', total:'Всего посчитано', checked:'проверено', undo:'Отменить', redo:'Повторить', add:'Добавить', selected:'Выбранная позиция', empty:'Ничего не найдено.', backup:'Скачать резервную копию', restore:'Восстановить копию', backupHint:'Все сессии и настройки в файле JSON.', restoreHint:'Заменить данные резервной копией. Можно отменить.', export:'Экспорт подсчёта (CSV)', reset:'Очистить этот подсчёт', resetHint:'Обнулить все количества. Можно отменить.', newHint:'Сохранить текущий подсчёт в истории и начать новый с теми же позициями.', name:'Название', edit:'Изменить', remove:'Удалить', ungrouped:'Другие позиции', categories:'Категории', details:'Позиция', quantity:'Количество', set:'Задать количество', bulk:'Добавить стопку', perRow:'В ряду', rows:'Рядов', apply:'Применить', move:'Порядок позиций', moveHint:'Перемещайте позиции стрелками внутри категории.', confirm:'Подтвердить', cancel:'Отмена', voice:'Голосовой подсчёт', voiceHint:'Выберите позицию и скажите «плюс пять». Доступность зависит от браузера и соединения.', stopVoice:'Остановить запись', reload:'Обновить приложение', ready:'Доступно без сети' },
  zh: { sessions:'记录', newCount:'新建计数', untitled:'未命名计数', saved:'已保存在此设备', offline:'离线 · 已保存在此设备', yourItems:'物品', hint:'点击 +1 · 滑动 −1 · 长按查看更多', search:'查找物品…', total:'总计', checked:'已检查', undo:'撤销', redo:'重做', add:'添加物品', selected:'选中的物品', empty:'未找到物品。', backup:'下载备份', restore:'恢复备份', backupHint:'所有记录和设置保存为 JSON 文件。', restoreHint:'用备份替换当前数据。可以撤销。', export:'导出计数 (CSV)', reset:'清空此计数', resetHint:'将所有数量设为零。可以撤销。', newHint:'保留当前记录，并使用相同物品开始新计数。', name:'名称', edit:'编辑', remove:'删除', ungrouped:'其他物品', categories:'类别', details:'物品详情', quantity:'数量', set:'设置数量', bulk:'批量添加', perRow:'每行', rows:'行数', apply:'应用', move:'调整顺序', moveHint:'使用箭头在类别内移动物品。', confirm:'确认', cancel:'取消', voice:'语音计数', voiceHint:'选择物品，然后说“加五”。可用性取决于浏览器和网络。', stopVoice:'停止聆听', reload:'重新加载更新', ready:'可离线使用' },
};
const deletion = {
  en: { deleteHint:'Delete this item and its quantity? You can undo this until the app is reloaded.', deleteCategoryHint:'Keep the items without a category, or delete the category and its items? You can undo this until the app is reloaded.' },
  lv: { deleteHint:'Dzēst šo vienību un tās daudzumu? To var atsaukt līdz lietotnes pārlādei.', deleteCategoryHint:'Saglabāt vienības bez kategorijas vai dzēst kategoriju kopā ar vienībām? To var atsaukt līdz pārlādei.' },
  ru: { deleteHint:'Удалить позицию и её количество? Можно отменить до перезагрузки приложения.', deleteCategoryHint:'Сохранить позиции без категории или удалить вместе с категорией? Можно отменить до перезагрузки.' },
  zh: { deleteHint:'删除此物品及其数量？重新加载应用前可以撤销。', deleteCategoryHint:'保留物品并移出类别，还是删除类别及其物品？重新加载前可以撤销。' },
};
export function translate(lang, key) { return deletion[lang]?.[key] ?? extra[lang]?.[key] ?? I18N[lang]?.[key] ?? extra.en[key] ?? I18N.en[key] ?? key; }
